CREATE TABLE STUDENT(
Nnumber VARCHAR(9),
Ssn CHAR(11) UNIQUE NOT NULL,
Caddress VARCHAR(300),
Cphone CHAR(12),
Pphone CHAR(12),
Bdate CHAR(10),
Sex VARCHAR(7),
Gclass VARCHAR(10),
Major_dep VARCHAR(20),
Minor_dep VARCHAR(20),
Degree_prm VARCHAR(15),
Fname VARCHAR(20),
Mname VARCHAR(20),
Lname VARCHAR(20),
City VARCHAR(30),
Cstate CHAR(2),
Zip CHAR(5),
PRIMARY KEY (Nnumber),
FOREIGN KEY (Minor_dep) REFERENCES DEPARTMENT (OfficeName),
FOREIGN KEY (Major_dep) REFERENCES DEPARTMENT (OfficeName));

CREATE TABLE DEPARTMENT (
OfficeName VARCHAR(50) NOT NULL,
Dept_Code VARCHAR(4) UNIQUE NOT NULL,
OfficeNumber CHAR(4),
OfficePhone CHAR(12),
PRIMARY KEY (OfficeName));



CREATE TABLE COURSE ( 
Course_Name VARCHAR(30) NOT NULL, 
Course_Description VARCHAR(300), 
Course_Num CHAR(7),
Semester_Hours INT, 
Lvl INTEGER,  
Offering_Dep VARCHAR(30) NOT NULL, 
PRIMARY KEY (Course_Num)); 

CREATE TABLE COURSE_SECTION (
Instructor VARCHAR(30) NOT NULL,
Semester VARCHAR(20) NOT NULL,
Year INT,
CONSTRAINT Year CHECK (Year > 1999),
Course VARCHAR(20)  NOT NULL,
Scourse_Num CHAR(7),
Section_Number CHAR(7),
Grade VARCHAR(3) NOT NULL,
PRIMARY KEY (Section_Number));

ALTER TABLE STUDENT ADD FOREIGN KEY (Minor_dep) REFERENCES DEPARTMENT (OfficeName);
ALTER TABLE STUDENT ADD FOREIGN KEY (Major_dep) REFERENCES DEPARTMENT (OfficeName);

ALTER TABLE COURSE ADD FOREIGN KEY (Offering_Dep) REFERENCES DEPARTMENT (OfficeName);

ALTER TABLE COURSE_SECTION ADD FOREIGN KEY (Scourse_Num) REFERENCES COURSE (Course_Num);

ALTER TABLE COURSE DROP CONSTRAINT Semester_Hours;
ALTER TABLE COURSE DROP CONSTRAINT Lvl;

ALTER TABLE COURSE_SECTION DROP COLUMN GRADE;

ALTER TABLE COURSE_SECTION
MODIFY Section_Number VARCHAR(7);

ALTER TABLE COURSE
MODIFY Offering_Dep VARCHAR(50);
ALTER TABLE STUDENT
MODIFY Major_Dep VARCHAR(50);

ALTER TABLE STUDENT
MODIFY Minor_Dep VARCHAR(50);

ALTER TABLE STUDENT DROP CONSTRAINT SYS_C0020285;
ALTER TABLE STUDENT DROP CONSTRAINT SYS_C0020284;
ALTER TABLE STUDENT ADD FOREIGN KEY (Major_dep) REFERENCES DEPARTMENT (OfficeName);

CREATE TABLE GRADEREPORT (
Gnnumber VARCHAR(9) NOT NULL,
Gsemester VARCHAR(20) NOT NULL,
Gyear INT NOT NULL,
Gcourse_num CHAR(7) NOT NULL,
Gsection_num VARCHAR(7) NOT NULL,
Grade CHAR(1),
FOREIGN KEY (Gnnumber) REFERENCES STUDENT (Nnumber),
FOREIGN KEY (Gcourse_num) REFERENCES COURSE (Course_Num),
FOREIGN KEY (Gsection_num) REFERENCES COURSE_SECTION(Section_Number));

ALTER TABLE GRADEREPORT
MODIFY Grade CHAR(3);